site_name: Actions Playground
repo_url: https://github.com/plannigan/actions-playground
repo_name: plannigan/actions-playground
docs_dir: docs
nav:
  - Overview: index.md
theme: material
extra_css:
  - css/version-select.css
extra_javascript:
  - js/version-select.js
