# version bumping
[tool.hyper-bump-it]
current_version = "0.15.0"

[tool.hyper-bump-it.git.actions]
commit = "create-and-push"
branch = "create-and-push"

[[tool.hyper-bump-it.files]]
file_glob = "docs/index.md"

[tool.hatch.envs.default]
description = "Test and lint the project code"
dependencies = [
    "black==23.11.0",
]