name: "Initialize Hatch"
description: "Install hatch & create an environment"
inputs:
  environment-name:
    description: "Which environment to create"
    default: "default"
    required: false
  activate:
    description: "If the environment should be activated after creation"
    default: "false"
    required: false
runs:
  using: "composite"
  steps:
    - name: "Install hatch"
      run: "pip install -r requirements-bootstrap.txt"
      shell: "bash"
    - name: "Create environment"
      env:
        ENVIRONMENT_NAME: "${{ github.event.pull_request.title }}"
      run: 'hatch --verbose env create "${ENVIRONMENT_NAME}"'
      shell: "bash"
    - name: "Activate environment"
      if: "${{ inputs.activate == 'true' }}"
      env:
        ENVIRONMENT_NAME: "${{ github.event.pull_request.title }}"
      run: 'source $(hatch env find "${ENVIRONMENT_NAME}")/bin/activate'
      shell: "bash"
