name: "Initialize Hatch"
description: "Install hatch & create an environment"
inputs:
  environment-name:
    description: "Which environment to create"
    default: "default"
    required: false
outputs:
  venv-path:
    description: "Absolute path to created virtual env"
    value: ${{ steps.env-path.outputs.venv-path }}
runs:
  using: "composite"
  steps:
    - name: "Install hatch"
      run: "pip install -r requirements-bootstrap.txt"
      shell: "bash"
    - name: "Create environment"
      env:
        ENVIRONMENT_NAME: "${{ inputs.environment-name }}"
      run: 'hatch --verbose env create "${ENVIRONMENT_NAME}"'
      shell: "bash"
    - name: "Retrieve venv path"
      id: env-path
      env:
        ENVIRONMENT_NAME: "${{ inputs.environment-name }}"
      run: echo "venv-path=$(hatch env find "${ENVIRONMENT_NAME}")" >> $GITHUB_OUTPUT
      shell: "bash"
