name: CI

# Triggers the workflow on push or pull request
# events but only for the main branch
on: [push, pull_request]

env:
  PYTHON_VERSION: "3.9"

jobs:
  simple-test:
    runs-on: ubuntu-latest
    steps:
      - name: Always passes
        run: echo "Success"

  build-docs:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup git user
        uses: ./.github/actions/configure-git-user

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Publish current dev version
        if: github.ref == 'refs/heads/main'
        run: mike deploy --push dev
