name: CI

on:
  pull_request: {}
  push:
      branches: ["main"]

env:
  PYTHON_VERSION: "3.9"

jobs:
  simple-test:
    runs-on: ubuntu-latest
    steps:
      - name: Always passes
        run: echo "Success"

  upload-two-artifacts:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Create files
        run: |
          mkdir files
          echo "hello" > files/hello.txt
          echo "world" > files/world.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: files/

  update-dev-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Show artifacts
        run: |
          ls -al
          cat *.txt
