name: CI

on:
  pull_request: {}
  push:
      branches: ["main"]

env:
  PYTHON_VERSION: "3.9"

jobs:
  simple-test:
    runs-on: ubuntu-latest
    steps:
      - name: Always passes
        run: echo "Success"

  upload-two-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Create files
        run: |
          mkdir files
          echo "hello" > files/hello.txt
          echo "world" > files/world.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: files
          path: files/
          if-no-files-found: error

  use-hatch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Initialize Hatch
        id: init-hatch
        uses: ./.github/actions/initialize-hatch
        with:
          environment-name: "default"
      - name: Show Environment
        run: |
          echo ${{ steps.init-hatch.outputs.venv-path }}
          echo ${PATH}
          "${{ steps.init-hatch.outputs.venv-path }}"/bin/pip list

  update-dev-docs:
    runs-on: ubuntu-latest
    needs: ["upload-two-artifacts"]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
            name: files
            path: dist

      - name: Show artifacts
        run: |
          ls -al
          ls -al dist
          cat dist/*.txt
