name: CI

on:
  pull_request: {}
  push:
      branches: ["main"]

env:
  PYTHON_VERSION: "3.9"

jobs:
  simple-test:
    runs-on: ubuntu-latest
    steps:
      - name: Always passes
        run: echo "Success"
  hatch-shell:
    runs-on: ubuntu-latest
    steps:
      - name: install hatch
        run: pip install hatch
      - name: run something in the shell
        run: |
          ls -al
          pwd
          echo ${GITHUB_WORKSPACE}
          ./hatch-shell.sh
        shell: bash

  upload-two-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Create files
        run: |
          mkdir files
          echo "hello" > files/hello.txt
          echo "world" > files/world.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: files
          path: files/
          if-no-files-found: error

  update-dev-docs:
    runs-on: ubuntu-latest
    needs: ["upload-two-artifacts"]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
            name: files
            path: dist

      - name: Show artifacts
        run: |
          ls -al
          ls -al dist
          cat dist/*.txt
