name: Merged PR

on:
  pull_request:
    types:
      - "closed"
    branches:
      - "main"


jobs:
  store-event:
    runs-on: ubuntu-latest
    steps:
      - name: Copy to static location
        run: |
            cp "${GITHUB_EVENT_PATH}" event.json
      - uses: actions/upload-artifact@v2
        with:
          name: event
          path: event.json
