name: Merged PR

on:
  pull_request:
    types:
      - "closed"
    branches:
      - "main"


jobs:
  store-event:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v2
        with:
          name: event
          path: ${{ env.GITHUB_EVENT_PATH }}
